CREATE TABLE dbconference.talk(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  SPEAKER_NAME varchar(255) NOT NULL,
  TYPE_TALK varchar(30) NOT NULL,
  CONFERENCE_ID bigint(20) NOT NULL ,
  PRIMARY KEY (ID),
  KEY fk_conference (CONFERENCE_ID),
  CONSTRAINT fk_conference FOREIGN KEY (CONFERENCE_ID)
      REFERENCES conference (ID) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;